### ISSUE TITLE
AWS DNSHealthCheck

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#105]
**Use Case**

As a gateway admin managing a set of gateways across multiple clusters, I want to define a common health check that will govern whether a DNS A record is considered healthy so that with a single policy, I can ensure the DNS response for services exposing endpoints and using listeners on my gateway are only returning endpoints that are from healthy service endpoints allowing us to automatically and rapidly mitigate an unexpected outage. I also want to define a strategy for if all the endpoints become available. I want to define a minimum number of records per hostnames so that my health check doesn't remove all records . 

**What**
This is an API that targets a gateway and encapsulates an end point check. We should base it on what we provided via annotations in the GLBC https://github.com/kcp-dev/kcp-glbc/blob/main/docs/dns/health-checks.md

**Constraint**
At this point the endpoint has to be publicly reachable. In the future we may look at other forms of check that do not require this. Example something running at the gateway level that performs the check and reports back via a status condition on the listeners status block

- [x] #98 
- [x] #106 
- [x] #107

**Comment by david-martin** [comment]
Closing as done.
@sergioifg94 to create a new issue for provider agnostic health checks
