### ISSUE TITLE
Add DNSHealthCheck Controller

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#106]
**What**

Add a new healthcheck controller under a dns package. This controller is responsible for reconciling the DNSHealthCheck
- Validate the target and spec of the DNSHealthCheck
- For each defined listener in the Gateway, add a health check to the DNSRecord ( we can modify the spec of the DNSRecord to support health checks)
- This controller should be triggered by changes to the DNSRecord, Gateway and DNSHealthCheck resources. DNSHealthCheck should probably be owned by the gateway it is targeting so it is removed if the gateway is removed
- The status of the DNSHealthCheck should reflect whether the check is considered active
- Another option is to add a status listener condition that informs that a health check is active for that listener

**Comment by sergioifg94** [comment]
@philbrookes Yep, closing it. Thanks Phil
