### ISSUE TITLE
Add e2e test for DNSHealthCheck

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#107]
**What**

Beyond regular unit tests, we should add an e2e test for the DNSHealthCheck. This test would not need to directly change the DNSProvider but could use a mock client for that piece. We would want to test that the HealthCheck was reconciled correctly, the DNSRecord was updated correctly and any additonal status on the gateway added along with the reverse flow for deletion. 
The test should also validate that we do not reconcile badly defined health checks

**Comment by philbrookes** [comment]
https://github.com/Kuadrant/multicluster-gateway-controller/pull/226
