### ISSUE TITLE
Advanced Sync Support

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#108]
#43 introduced the sync component and enabled us to be able to connect to the control plane, sync resources and report status back to the control plane. 
This is a good foundation but there are several pieces that are needed in order to bring the sync component to a full MCVP

- [x] Add capability to apply transforms to the gateway declared by the control plane (IE the gateway class to use)
- [x] Remove MCTC annotations from downstream resource.
- [x] Add deletion support based on deletion of resources in the CP
- [x] Replace hardcoded downstream namespace
- [x] Unit tests that cover the key functionality of the above sync features
- [x] Add e2e tests that cover sync functionality

**Comment by maleck13** [comment]
@philbrookes could you review please. Also feel free to add new or break up into issues if that works better for estimation etc

**Comment by philbrookes** [comment]
> 

Sure, was wondering about that myself.

**Comment by maleck13** [comment]
https://github.com/Kuadrant/multicluster-gateway-controller/issues/131 follow up
