### ISSUE TITLE
Control Plane Gateway status

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#113]
**What**

The control plane Gateway status should provide a rolled up view of the status of the per gateways it represents. It should also represent the condition of policies attached to those gateways.

- [x] Define what our CP gateway status will contain and communicate
- [x] Implement the rolled up status

Note for the policies at the CP level each of these should add in a status condition to the control plane gateway status which is not part of this work

**Comment by david-martin** [comment]
Proposal for aggregation https://github.com/Kuadrant/multicluster-gateway-controller/pull/150
