### ISSUE TITLE
Multi-Cluster rate limit

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#116]
**What**

Being able to define a rate limit policy within the multi-cluster control plane based on a multi-cluster topology that are informed by the multi-cluster topology and are enforced by the data plane.

**Status**
When defining a multi-cluster gateway and defining a RLP targeting that gateway. Understanding the status of the rate limiting on a given cluster is important from a admin using the control plane point of view. When I have created a RLP targeting a mc gateway, I also want to know that it has been synced and applied to the underlying clusters. 
Ideally I think we would add a aggregated status to the RLP but also a  condition to the gateway status. 

On the gateway it should be an all or nothing IMO. IE is my gateway protected or not

```
 - lastTransitionTime: "2023-04-14T14:46:18Z"
    message: Rate Limit Policy  $name applied to all gateways
    observedGeneration: 1
    reason: Applied
    status: "True"
    type: Applied

```

On the RLP it should probably provide a condition for each target cluster?

```
 - lastTransitionTime: "2023-04-14T14:46:18Z"
    message: Rate Limit Policy  $name applied to gateway on $cluster
    observedGeneration: 1
    reason: Applied
    status: "True"
    type: Applied

```

Only if all RLP conditions are True can the gateway be True 
https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/status_aggregation.md

**Why**

- Being able to declare policy in the same place you create your multi-cluster gateway have that policy be distributed to and applied to multiple instances of a gateway and enforced in that gateways data plane
- Having the attributes of your cluster topology automatically available as well known descriptors allows for simpler and richer options for providing rate limits based on your infrastructure

**Use Cases**

*Infra Rate Limiting*

As a gateway administrator, I want to define a limit that restricts the total number of requests that each instance of a uniform gateway will safely handle within a set period of time before beginning to reject requests so that I can ensure my gateway will remain up and running and importantly my cluster resources are protected so that I can access the cluster to restrict the gateway or certain users/IPs further. As instances of this gateway is running on multiple clusters, I want to define this limit in a single place that allows it to target my gateway definition

*Global Rate Limiting*

As a gateway administrator, I want to define a default limit per identifier of my choice to restrict access to endpoints exposed via my multi-cluster gateway to a sane default and ensure no unprotected endpoint is exposed that may allow consuming the entire limit for the gateway and provide fair access by default to those accessing endpoints attached to the gateway. I want to define this in the same place I define and manage my multi-cluster gateway

- [x] Install Rate Limiting CRD into the control plane 
- [x] Add new Rate Limiting Controller to the Gateway Traffic Controller
- [x] Add Transforms to inject cluster specific attributes
- [ ] Add a multi-cluster gateway and RLP status

**Demo Outline**

- Define a gateway and place it onto two data plane clusters with Kuadrant installed
- Deploy HTTPRoute to the gateway
- Observe no rate limiting happening
- Define a RLP at the control plane targeting the gateway 
- Observe that the attributes of the clusters are added to each RLP that is synced (control plane added these)
- Observe that requests are limited based on the header
- Define a new limit based with a variable based on the cluster id (which has been injected as a descriptor)
- Observe each user limited regardless of the cluster they hit
- Define a more restrictive limit for /upload that targets the HTTPRoute attached to the gateway
- Observe the more restrictive limit now takes effect

The above assumes the following
- Kuadrant installed on each DP cluster
- Some form of shared storage between the DP clusters

**Comment by maleck13** [comment]
@mikenairn @guicassolato @alexsnaps

**Comment by mikenairn** [comment]
@maleck13 8 maybe?
