### ISSUE TITLE
Allow a grace period strategy when a Gateway is displaced from a cluster

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#138]
If the placment rules or decisions change for a Gateway it may require the deletion of a Gateway on 1 or more data plane clusters.
If that happens, traffic may still resolve the Gateway IP for the displaced gateway and send traffic to it for some time after DNS records have been updated.

A grace period should be allowed for, before the Gateway is displaced to ensure the traffic dropped is kept low.

Depends on #52

**Comment by maleck13** [comment]
I wonder could this be part of the DNSPolicy "DNSGracePeriod" where we have a sane default of 2x TTL

**Comment by philbrookes** [comment]
PR: https://github.com/Kuadrant/multicluster-gateway-controller/pull/288
