### ISSUE TITLE
Bug: gateway reconciler going insane

### ISSUE THREAD

**Issue by makslion** [Kuadrant/multicluster-gateway-controller#143]
## What 
Once in a while, it was spotted that the gateway reconcilers get triggered multiple times a second.  No error messages in the logs.  The only change on the `Gateway` CR would be the `resourceVersion` field

## How is it supposed to be
In the current implementation, it should either go off once or requeue every 10 seconds. The only case or requeue without an error message would be if `gatewayHasAttachedRoutes` is set to false [here](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/pkg/controllers/gateway/gateway_controller.go#L276-L279)  

## Reproduction 
That is tricky to catch, Sometimes it constantly happens this usually happens on clusters that have been up a while but have also happened on fresh clusters too. Another scenario we are seeing is on a "fresh" the reconciler goes insane for ~10-15 seconds reaching the `resourceVersion` count of 20-30 hundred and then falls back to a normal requeue of 10 seconds.

**Comment by maleck13** [comment]
going to close this as I don't believe this is an issue once the ocm branch merged
