### ISSUE TITLE
Update Local Setup to work with OCM (Istio / OLM)

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#159]
**What**

Change local setup to instal OLM and Istio and no longer install kuadrant.

**Comment by philbrookes** [comment]
diff - https://github.com/Kuadrant/multicluster-gateway-controller/compare/main...philbrookes:multi-cluster-traffic-controller:gh-159?expand=1

branch: https://github.com/philbrookes/multi-cluster-traffic-controller/tree/gh-159
