### ISSUE TITLE
Update the control plane RateLimitPolicy logic to use OCM policy framework to sync/enforce the resource 

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#176]
Following on from #163, and using #175 as a base,
Update the controller logic to leverage the policy framework in OCM to push the RateLimitPolicy into relevant clusters.

The RateLimitPolicy will be wrapped into a Policy resource.
Since a Gateway will reference a Placement (via labels), the controller will be able to lookup the targetRef of a RateLimitPolicy and create the PlacementBinding, thereby binding the Policy to the Placement.

The Policy compliance state should be propagated back to the RateLimitPolicy status.

There is example code that does similar things in https://github.com/david-martin/multicluster-service-policy-controller/blob/main/internal/controller/multiclusterservicepolicy_controller.go#L130-L177

**Comment by david-martin** [comment]
Closing issue and draft PR #181

Although the concept of a RateLimitPolicy defined at the control plane was implemented using the syncer approach, after conversations with @maleck13 and some others, it was determined that brining this policy up to the control plane is not in scope for an MVP.

IMO the use case needs to be more concrete before adding back support for this.
If/when that happens, it would likely the OCM  approach for syncing the resource via the Policy Framework as was partially proven in the draft PR #181 

cc @mikenairn 
When #175 lands on main, the existing approach using the syncer to push the RLP down to data plane clusters will no longer be used (as the syncer will be replaced by OCM and the ManifestWork API). Rather than have broken/incomplete functionality then, we should strip out the RLP controller.
I can get a PR together to do that, but want to make sure you're aware of the decision here and rationale.

**Comment by mikenairn** [comment]
> cc @mikenairn When #175 lands on main, the existing approach using the syncer to push the RLP down to data plane clusters will no longer be used (as the syncer will be replaced by OCM and the ManifestWork API). Rather than have broken/incomplete functionality then, we should strip out the RLP controller. I can get a PR together to do that, but want to make sure you're aware of the decision here and rationale.

Fair enough, but what was the rationale exactly?

**Comment by david-martin** [comment]
> Fair enough, but what was the rationale exactly?

In terms of policies that add value in the control plane, DNS based ones like weighting/geo/failover provide more value in an MVP to a gateway admin.
Personally I don't think the story around a cross cluster RLP is clear or validated yet (at least for shared counters). There's also additional work on counter syncing strategy that would need to be done (@alexsnaps has a lot of thoughts in this area).

That being said, I do think the concept of defaults and/or overrides makes sense (targetting the gateway vs. targetting a HttpRoute). That would be satisifed by https://gateway-api.sigs.k8s.io/geps/gep-713/#inherited-policy-attachment in the data plane.

@maleck13 Anything I missed here?

**Comment by maleck13** [comment]
Final update on this one. We have a plan that will not tie our policy controller to istio specifically allowing it to continue to be used with other gateway providers to do multi-cluster DNS etc
