### ISSUE TITLE
ManagedZone per namespace

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/multicluster-gateway-controller#202]
**What**

A managed zone must exist in order for an DNSRecords to be created (DNSRecord belongs to a managed zone).  Currently a ManagedZone is created as part of local-setup in the multi-cluster-traffic-controller-system namespace (https://github.com/Kuadrant/multicluster-gateway-controller/tree/main/config/local-setup/controller). This in turn is used as a fallback during the Managed Zone lookup if no matching managed zone is found in the current gateway namespace. This logic should be removed and instead only ManagedZones within the same namespace as the Gateway will be considered.

**Why**

We might eventually want to share ManagedZones between namespaces, but this logic is not the way to do it. Until better logic exists (ReferenceGrant maybe https://gateway-api.sigs.k8s.io/api-types/referencegrant), it will be required for a user to create a ManagedZone in the same namespace as the Gateway using it.

- [x] Update manage zones controller logic 
- [x] Add e2e test for managed zones
- [x] Document using a ManagedZone

**Comment by philbrookes** [comment]
integration tests PR: https://github.com/Kuadrant/multicluster-gateway-controller/pull/251

**Comment by philbrookes** [comment]
documentation PR: https://github.com/Kuadrant/multicluster-gateway-controller/pull/257
