### ISSUE TITLE
Remove Syncer Code ⚰️

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#229]
**What**

We are now leveraging OCM, the sync component is no longer needed

- Syncer component code
- Any reference to the annotations 
- Any reference in the local-setup
- Any ref in the docs / readme
- Write a brief eulogy in the form of a Limerick

**Comment by philbrookes** [comment]
PR: https://github.com/Kuadrant/multicluster-gateway-controller/pull/264

**Comment by philbrookes** [comment]
```
There was a young syncer from KCP
who always synced things quite happily
He worked hard no doubt
but KCP didn't work out
so the young syncer was executed rapidly
```
