### ISSUE TITLE
Walkthrough based e2e test

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#266]
**What**

We effectively want to execute the walkthrough commands here as a test
https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/how-to/ocm-control-plane-walkthrough.md 

We should make the number of placement clusters an option as we only have one hosted cluster right now. Whereas when running it locally we might want to increase the number of clusters.

In the future we are adding support for more DNS Providers, so we will want to be able to add more providers to the test cases over time (this will depend on the work to add a DNSProvider resource) but is something to keep in mind while working on the test

**Outcome**

A github based execution that runs through most of the steps outlined in our walkthrough against a target cluster. Rather than curling the endpoint we can likely rely on a dig type command here to see that the DNS has been updated in the DNS Provider.

**Comment by maleck13** [comment]
@roivaz @mikenairn FYI

**Comment by maleck13** [comment]
@roivaz noticed this https://github.com/Kuadrant/multicluster-gateway-controller/pull/243 is the above covered by that ?

**Comment by roivaz** [comment]
Hey, indeed, I basically followed the walkthrough to write those few tests. Right now it can run in a single cluster (hub+spoke) or in two clusters, one for the hub and one for a single spoke. I actually already have a working github action in my fork (https://github.com/roivaz/multicluster-gateway-controller/actions/runs/5280709156/jobs/9553217731), running against the local-setup.

You also mention our hosted cluster, but all work there was stopped and the issues closed as we were no longer pursuing a saas offering. Some amount of work would be required to bring it up to date (it's still running with the older syncer approach).

**Comment by maleck13** [comment]
Yes I think it would be worth bringing that cluster up to date at some point as it is OCP also. Ok I will close this issue as you have already covered the need which is awesome
