### ISSUE TITLE
Remove unhealthy DNS Records from DNS provider

### ISSUE THREAD

**Issue by sergioifg94** [Kuadrant/multicluster-gateway-controller#272]
## What

In order to support the ability of endpoints to be taken down when the associated health check fails, we must implement the logic in the DNSRecord controller to watch for status updates in the associated DNSHealthCheckProbe, and disable the endpoint if the endpoint is unhealthy and the number of consecutive failures is greater than the failure threshold configured in the DNSPolicy, as well as re-enable it when it becomes healthy again.

This removal of a DNS Record will need to cascade through the DNS Record to ensure no dead-ends are created where a CNAME has no records to resolve to.

## DNS Record Structure Diagram:
https://lucid.app/lucidchart/2f95c9c9-8ddf-4609-af37-48145c02ef7f/edit?viewport_loc=-188%2C-61%2C2400%2C1183%2C0_0&invitationId=inv_d5f35eb7-16a9-40ec-b568-38556de9b568

## How

When a DNS health check probe is failing, it will update the DNS Record CR with a custom field on that endpoint to mark it as failing.

There are then 3 scenarios which we need to consider:
1 - All endpoints are healthy
2 - All endpoints are unhealthy
3 - Some endpoints are healthy and some are unhealthy.

In the cases 1 and 2, the result should be the same: All records are published to the DNS Provider.

When scenario 3 is encountered the following process should be followed:
- For each gateway IP or CNAME: this should be omitted if unhealthy.
- For each managed gateway CNAME: This should be omitted if all child records are unhealthy.
- For each GEO CNAME: This should be omitted if all the managed gateway CNAMEs have been omitted.
- Load balancer CNAME: This should never be omitted.

If we consider the DNS record to be a hierarchy of parents and children, then whenever any parent has no healthy children that parent is also considered unhealthy. No unhealthy elements are to be included in the DNS Record.

**Comment by maleck13** [comment]
@philbrookes this is done in the DNS policy controller now under reconcileGatewayDNSRecords
