### ISSUE TITLE
Package multicluster-gateway-controller as an OLM bundle

### ISSUE THREAD

**Issue by ficap** [Kuadrant/multicluster-gateway-controller#276]
Make multicluster-gateway-controller installable via OLM. Custom built catalog image pushed to quay.io/kuadrant will suffice for now.

**Comment by maleck13** [comment]
This has moved to the current iteration

**Comment by R-Lawton** [comment]
* able to generate the bundle
* able to make it available in a cluster via a catalog (can be our own for now)
* able to install MGC and add-on manager via a subscription when OLM installed
* docs
* Github CI
* Stable channel

**Comment by maleck13** [comment]
https://github.com/Kuadrant/multicluster-gateway-controller/pull/491
