### ISSUE TITLE
Add a community page

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#285]
Add a community page to the kuadrant.io website that explains where and how to get involved with the community

https://kubernetes.io/community/

- [ ] add code of conduct
- [ ] where to get involved with discussion
- [ ] Videos
- [ ] Contributor Guide
- [ ] Socials

**Comment by jasonmadigan** [comment]
https://github.com/Kuadrant/multicluster-gateway-controller/issues/285
