### ISSUE TITLE
Improve getting started experience

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#286]
**What**

Currently out best "Getting started guide" is to go through the OCM walkthrough. While this works, it is a lot of work. 

**Proposal**

create a page similar to this:

https://open-cluster-management.io/getting-started/quick-start/

that has pre-reqs and a script based setup. This page should also explain what we are going to setup and perhaps link to the more detailed walkthrough doc

Prereqs:
- Kind installed

**Create a new script ** that is for locally trying the system

that prompts for the root domain, and AWS creds if not present
installs OCM and Istio (which we already do)
sets up the ground work in the OCM walkthough (IE two kind clusters, Istio installed, kuadrant (MGC and Data plane) installed via latest images and hooked up, clusterset set up and bound, placement created that targets the clusterset)
Essentially once it is done, they get to create a gateway, create a HTTPRoute and see it work. We should then have follow ons for using the RateLimit policy and creating / updating the DNS Policy 

- [x] new script to get you to the point you can create a gateway
- [ ] update the getting started page for kuadrant.io and github readme ( Link to the follow ons ie (rate limiting))

**Comment by david-martin** [comment]
@maleck13 Is this different than #280, which is part of the [Kuadrant.io Refresh](https://github.com/Kuadrant/multicluster-gateway-controller/issues/205)

**Comment by maleck13** [comment]
yeah I would say this is a quick start whereas the install guide should prob be more focused on actual installation rather than setting up placements and clusters for you

**Comment by laurafitzgerald** [comment]
As part of this task i'm starting with stepping through https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/how-to/ocm-control-plane-walkthrough.md
I've made a copy of that document here https://docs.google.com/document/d/1cLtLNT9HqGqfQCntpEUIqaX22LMUrHQ8VrRuqIqHswc/edit where myself and @eoinfennessy are making notes about potential improvements as well as discussion about a script.

**Comment by laurafitzgerald** [comment]
Hey @maleck13 or anyone. i've been looking at the existing script local-setup.sh to see what can be done for a quick start one line setup. There's a lot that that existing one relies on locally. configuration files and helm charts kept in the config directory and helper functions. before starting into it I want to double check on an approach. i'm new to helm so wondering if those resources can be gotten dynamically somehow? the alternative feels like we'll end up with a massive script which duplicates some of the existing work. did you have any other approach in mind as a preference for this?
