### ISSUE TITLE
Refactor health check logic and DNS reconciler logic to create / update the DNS Record CR in one place.

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/multicluster-gateway-controller#294]
Currently the Health checks are injected into the DNS Record from a separate place to where the DNS Record is initially created. This makes it more complicated to reconcile the DNS Record CRs, we should centralize this logic so we can reason about the spec of the DNS Record more easily.

**Comment by maleck13** [comment]
@philbrookes is this still relevant? It is currently in the backlog
