### ISSUE TITLE
create an architectural overview doc

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#297]
**What**

Provide an architectural overview doc to give a clear view of how the different components fit together what their responsibilities are and the main data flows and interaction flows

**Comment by laurafitzgerald** [comment]
@maleck13 if you think this doc might be useful on the kuadrant website, feel free to add a note about it to #404

**Comment by maleck13** [comment]
https://hackmd.io/WgStjGvDTlevQDLszWkVAw?both#Overview
