### ISSUE TITLE
Create an example Grafana dashboard that shows traffic data, leveraging Istio metrics

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#307]
*What*

Building on #305 & #306, design a set of dashboard panels that show traffic data flowing through the Gateway instances.
This task is deliberately vague as there's an element of investigation into what metrics are available, and what is useful to show.
It would be good to visualise the DNS load balancing features (geo & weighting) of MGC.
The [Istio Workload Dashboard](https://grafana.com/grafana/dashboards/7630-istio-workload-dashboard/) may serve as a good jump off point.

Optional Extra: Document why and what this dashboard solves

**Comment by roivaz** [comment]
Also, for 3scale SaaS we use some dashboards/alerts based on envoy metrics that might have also interesting things

* dashboards: https://github.com/3scale/platform/blob/master/manifests/apps/marin3r/base/grafanadashboard.yaml
* alerts: https://github.com/3scale/3scale-saas/blob/master/manifests/3scale-saas/backend/base/prometheusrules/backend-listener-envoy-prometheusrule.yaml

These are both private repos, so anyone that needs access just poing me.
