### ISSUE TITLE
DNSRecord reconciler can fall into a continuous loop on AWS API errors

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/multicluster-gateway-controller#310]
**What**

When an error is returned from the AWS API during a DNSRecord update the reconciler appears to continually try and make the same request forever. 

There also seems to be some issue with the status update of the DNSRecord where the endpoints list is incorrectly updated in certain cases, such as when there is an error returned.

To reproduce create a DNSRecord with an invalid spec and apply it.

- [x]  add status condition to reflect error
- [x]  Configure exponential back off for retry ensuring status reflects success or failure on retry

We should be able to to configure the retry and backoff via the controller runtime
https://github.com/kubernetes-sigs/controller-runtime/blob/16bf3ad036b908d897543c415fcc0bafc5cec711/pkg/controller/controller.go#L117

**Comment by maleck13** [comment]
@mikenairn add issue for ManagedZone
