### ISSUE TITLE
Managed Zone Support

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#34]
**What**

A managed zone represents a zone in an DNS Provider that is being managed by the traffic controller. Access to the provider is provided separately via credentials given to the traffic controller. In time these credentials will form the basis for a DNSProvider CR but initially there will just be one provider we support. 

**Considerations and Follow Ons**

- When should a zone be considered safe to delete
- How can we improve scalability (multiple providers, migration, shared zones)
  - As part of the above how would we migrate a tenant from a shared zone to a dedicated zone 

**User Story**

As a cluster administrator / Gateway administrator, I want to register a zone with the traffic controller to be used for my applications and multi-cluster ingress needs. I want this zone to be something I choose and own so that I know the application hosts are part of my well known "properties/domains". while still being able to take advantage of all the features offered by the traffic controller.

- [x] #35
- [x] Provide service/api to find which managed zone a host should be assigned

**Comment by mikenairn** [comment]
Related follow up task here https://github.com/Kuadrant/multicluster-gateway-controller/issues/202
