### ISSUE TITLE
BUG: Duplication of dnsname if no subdomain is used

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/multicluster-gateway-controller#347]
If no subdomain is used in the gateway and just the domain is used for example rlawton.hcpapps.net instead of test.rlawton.hcpapps.net the dnsrecord cr and in the dnsprovider both was and google will create records with a doubling of the name 

![Image](https://github.com/Kuadrant/multicluster-gateway-controller/assets/53817495/4f2afa49-30e8-4cd2-b35b-8f7cb436651e)

We should have a way to detect this and prevent users from doing it

**Comment by mikenairn** [comment]
Note, this isn't google specific, it's an issue with the logic around finding a ManagedZone for a listener host.
