### ISSUE TITLE
Kuberentes label selectors for the DNSPolicy custom settings

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/multicluster-gateway-controller#376]
**Proposal:** use proper [Kubernetes label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) to indicate the managed cluster resources that relate to a particular weighted load balancing custom config in a `DNSPolicy`, instead of the current [`value`](https://github.com/Kuadrant/multicluster-gateway-controller/blob/7027be4cdb264ebc6a185263754d99b821d61b32/pkg/apis/v1alpha1/dnspolicy_types.go#L55) field.

Other kinds of Kuadrant policies rely on label selectors for similar references between resources that are not direct references by name, e.g. https://github.com/Kuadrant/authorino/blob/579aff40bddd5863d997f77d6ce08b4af5e6b22c/api/v1beta1/auth_config_types.go#L282.

A couple advantages of using label selectors:
- Kubernetes users are usually familiar with those (or can refer to the Kubernetes docs);
- Implementation of the internal API call that effectively selects those related objects can be simplified;
- Support for exact label matchers and expressions (e.g. `kuadrant.io/az in (us, uk)`).

**Comment by mikenairn** [comment]
Thanks @guicassolato. Will take a look into it. If we have a similar pattern being used in our other policies I'd like to see if we can do that here.
