### ISSUE TITLE
Package dependencies for quickstart via Docker image

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#387]
**What**
Package the dependencies required to run the quickstart script into a Dockerfile so that the user doesn't need to complete a large set of pre-requisite steps.

Once dependencies are managed by the Dockerfile remove the reference to pre-requisites handled by the Dockerfile from https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/how-to/ocm-control-plane-walkthrough.md#requirements and https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/getting-started.md#pre-requisites

**Alternative**
Scriptify the `make dependencies` command so that the script will handle installation of dependencies

**How**
NOTE: the how is not currently solved but here is an example that was tried.

Sample Dockerfile
```
FROM registry.access.redhat.com/ubi8/ubi:8.1

WORKDIR /app

RUN dnf install -y curl tar

RUN curl -Lo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64 \
    && chmod +x /usr/local/bin/kind
```
Usage example
```
mkdir -p /tmp/mgc_bin
docker run --rm -v /tmp/mgc_bin:/usr/local/bin mgc-quickstart:test

chmod +x /tmp/mgc_bin/kind
export KIND_BIN=/tmp/kind_bin/kind
```

Error output is 
```[exec /usr/local/bin/kind: exec format error
/dev/stdin: line 5: /tmp/kind_bin/kind: cannot execute binary file](docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/kind": stat /usr/local/bin/kind: no such file or directory: unknown.)```

OR 
```chmod: /tmp/mgc_bin/kind: No such file or directory
/dev/stdin: line 5: /tmp/kind_bin/kind: cannot execute binary file```

**Comment by Ygnas** [comment]
**Why**

When you build a Docker image using the docker build command, by using the RUN command,  docker needs to send the entire context to the Docker daemon, that's why the dependencies were not found.

**How**

The modified Dockerfile uses CMD to download and install the dependencies when the container is run, instead of when the image is being built.

```
FROM registry.access.redhat.com/ubi8/ubi:8.1

WORKDIR /app

RUN dnf install -y curl tar

CMD ["sh", "-c", "\
    curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64 && \
    chmod +x kind && \
    curl -Lo newkind https://github.com/kubernetes-sigs/kind/releases/download/v0.11.0/kind-linux-amd64 && \
    chmod +x newkind"]
```

**Usage example**

```
mkdir -p /tmp/mgc_bin
docker run --rm -v /tmp/mgc_bin:/app image-name
```

The Docker container will now download the dependencies and install kind inside the container's **_/app_** directory, and you can access them from the mounted directory **_/tmp/mgc_bin_** on the host machine.

**Comment by laurafitzgerald** [comment]
@Ygnas thanks for this. after trying this "on my machine" the binary is not executable. because i'm on mac rather than linux. We could have the dockerfile be aware of the OS somehow and do the build inside the script but I think we could also go with the alternative of having the script install the dependencies. Basically what we do in https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/hack/make/dependencies.make only in the script itself. @eoinfennessy had been looking into that when we began talking about the Dockerfile idea. cc @mikenairn

**Comment by mikenairn** [comment]
I put a small sample Dockerfile and script together here based on how we would have done things like this in the past, might be helpful https://github.com/Kuadrant/multicluster-gateway-controller/commit/435c007b6cea6b9d3441874ab82aeab7b11b2f95

**Comment by mikenairn** [comment]
Another option that might work on both mac and linux since `--network=host` doesn't work on a mac. https://github.com/mikenairn/multi-cluster-traffic-controller/commit/d2a13c3d2d04d7d93b3767a4445634975a4d32c3

**Comment by eoinfennessy** [comment]
@mikenairn Really nice! Was able to use your image with a modified `quickstart-script.sh` to install OLM on the cluster using the `operator-sdk` binary contained on the container. I created a wrapper function to help simplify it's usage.
```
operatorSdkWrapper() {
  docker run -u $UID -v "/tmp/mgc:/tmp/mgc:z" --network mgc -e KUBECONFIG='/tmp/mgc/kubeconfig' --rm "quay.io/kuadrant/mgc-tools:latest" -c "operator-sdk $*"
}
```
I'm thinking the names of these functions could probably be set in place of the `*_BIN` variables used in functions sourced in the script? I'll try to do similar with the other binaries used in the script.

**Comment by laurafitzgerald** [comment]
Tested [this solution](https://github.com/mikenairn/multi-cluster-traffic-controller/commit/d2a13c3d2d04d7d93b3767a4445634975a4d32c3) on Mac and it worked. 🎉

**Comment by maleck13** [comment]
@eoinfennessy  @laurafitzgerald is this in progress?

**Comment by eoinfennessy** [comment]
@maleck changed status to 'In Progress' and created a [WIP PR here](https://github.com/Kuadrant/multicluster-gateway-controller/pull/415).
