### ISSUE TITLE
Allow the controller to be installed into existing hub using Kustomize

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#429]
**What**

While the quick start is great for trying it out when starting from nothing. Beyond "kicking the tires" we will also want people with existing OCM clusters to be able to install Kuadrant and use it. So the goal here is to start with the expectation that a hub cluster already exists and someone wants to use kustomize to install kuadrant into their hub to use to manage gateways.

**Comment by maleck13** [comment]
@mikenairn you may have more ideas here of how we can achieve this?

**Comment by david-martin** [comment]
Given that kustomize will be used for the script in #280, this issue will be solved as part of that.
Closing.
