### ISSUE TITLE
Don't rely on files in the repo for ocm-walkthrough

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#454]
**Why**
We don't want the ocm walkthrough to rely on any local git repo config.

**What**
Remove the use of files that exist in the ocm-walkthrough for kubeconfig context.
Potentially we could just have them contained in the commands themselves as with the yaml files for Gateway etc.

**Comment by laurafitzgerald** [comment]
cc @maleck13

**Comment by jasonmadigan** [comment]
Would this just be the kubeconfig's? IIRC most of the other commands in the how-to are heredocs.

**Comment by maleck13** [comment]
Is there an example of where we do this?

**Comment by laurafitzgerald** [comment]
There's two locations in the guide where we do `kind export kubeconfig` refering to `pwd/local`
