### ISSUE TITLE
Cleanup Overview docs.kuadrant.io

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#475]
**Why**
Currently the [Overview Section ](https://docs.kuadrant.io/multicluster-gateway-controller/) uses the [README of the github repo ](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/README.md) which contains a number of different ways to run the controller.
Since we recently added the [getting started](https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started/) having those other methods of installation being present in the first section could confuse the flow we want new users to take. 
 **What**
Clean up the flow. Options could include
- Remove the Overview link and point directly to the getting started, include the Description in the getting started
- Move the other methods of installation to some development doc and point to that as a developer option or the getting started as a try it out option

**Comment by jasonmadigan** [comment]
Will do this this as part of #476
