### ISSUE TITLE
Milestone 2 Documentation

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#48]
*Tasks*

- [x] #49
- [x] #50
- [x] #51

**Comment by maleck13** [comment]
@david-martin this is still open, will assign to milestone 3

**Comment by maleck13** [comment]
We get these tasks done first before kicking into m3 fully cc @mikenairn around docs for managed zone

**Comment by maleck13** [comment]
@philbrookes anything in place or in progress for docs around the syncer?
