### ISSUE TITLE
I should be able to follow the installation guide and install Kuadrant into an existing k8s cluster that meets version and dependency requirements

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#481]
**What**

Follow https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/installation/control-plane-installation.md and install kuadrant into an existing k8s cluster that meets the dependency requirements

Bugs should be logged as issues and linked to this issue

**Comment by sergioifg94** [comment]
Followed the guide using clusters created and set up manually, it all works well. Just created the linked PR to improve a bit about joining the spoke to the hub
