### ISSUE TITLE
I should be able to follow the DNSPolicy guide without errors or issues

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#486]
**what**

Follow https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dnspolicy-quickstart/ and ensure you can complete it without errors or issues

Bugs should be reported and linked to this issue

**Comment by laurafitzgerald** [comment]
the order of the pre-requisites and steps in the doc is a bit confusing. We link out to ManagedZone creation which links to the walkthrough and then mention gateway and httproute which is also covered by the walkthrough  
![Uploading Screenshot 2023-09-13 at 16.19.44.png…]()

The steps show a basic DNSPolicy but if you've followed the steps in the walkthrough you'll already have a DNSPolicy created. 
If the walkthrough isn't completed the DNSPolicy in the doc could be formatted better for easy creation although it asks for a gateway name and namespace which wouldn't be known if you were only following this document and didn't follow the walkthrough. If we expect the user to not follow this then pointing to how a gateway can be created and a httproute can be created. 

At the bottom we link to https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/ which seems to be a more in depth document about DNSPolicy which might be more useful to point to after going through the walkthrough?

**Comment by maleck13** [comment]
Hmm well I think it should def link to 
https://docs.kuadrant.io/multicluster-gateway-controller/docs/gateways/define-and-place-a-gateway/
looking at the MZ doc, it only has one line there about "there is also a walkthrough" so I don't see that as being to bad, as the rest of the doc looks to go into what a MZ is etc
Adding a link to  https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/  at the end of the walkthrough seems reasonable. 
Adding links to specific items in the quick start might also be reasonable
What next:
- Full Walkthrough (from where you are to the kitchen sink)
- Placing Gateways
- DNSPolicy
etc?

**Comment by mikenairn** [comment]
I'm not seeing the point of this doc https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dnspolicy-quickstart/, it doesn't seem to tell you anything that this one doesn't already explain https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/. We also don't have an equivalent "quickstart" doc for TLS so it's odd that the starting point for these looks different.

On this one https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/, health checks has been added in by default. When i started it, the first DNSPolicy was the most basic (just the targetRef), and you built on that as you went through it. IMO, health checks should be moved to the end of that doc as something you can add into your policy.

**Comment by maleck13** [comment]
> I'm not seeing the point of this doc https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dnspolicy-quickstart/, it doesn't seem to tell you anything that this one doesn't already explain https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/. We also don't have an equivalent "quickstart" doc for TLS so it's odd that the starting point for these looks different.

There is a lot of technical detail in https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/  (no bad thing), perhaps we merge these two docs into:

**Getting Started with DNSPolicy**
focused around a min set of resources to get you started
** Advanced Loadbalancing with DNSPolicy***
focused around GEO and Custom Weighting
**Unhealthy endpoint detection with DNSPolicy**
Health Checks
** More technical detail (IE dns record structure etc)?

**Comment by maleck13** [comment]
Agree on whatever we decide also applying to other policy APIs

**Comment by laurafitzgerald** [comment]
> I'm not seeing the point of this doc https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dnspolicy-quickstart/, it doesn't seem to tell you anything that this one doesn't already explain https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/. We also don't have an equivalent "quickstart" doc for TLS so it's odd that the starting point for these looks different.
> 

> On this one https://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dns-policy/, health checks has been added in by default. When i started it, the first DNSPolicy was the most basic (just the targetRef), and you built on that as you went through it. IMO, health checks should be moved to the end of that doc as something you can add into your policy.

I'd be in favour of making these changes.

**Comment by laurafitzgerald** [comment]
Follow on issue for this work https://github.com/Kuadrant/multicluster-gateway-controller/issues/544
