### ISSUE TITLE
Update DNSPolicy reconciler to function with non mgc gateways (e.g. istio)

### ISSUE THREAD

**Issue by makslion** [Kuadrant/multicluster-gateway-controller#496]
## What 
After the #311 the DNS Policy reconciler is no longer coupled with OCM. This enables us to process other Gateway Implementations. However, the logic, currently, implies that we are dealing with the multicluster gateways. 

https://github.com/Kuadrant/multicluster-gateway-controller/pull/465/files#r1324149471

## How 
- [x] Update reconciler logic to be suitable for both single- and multi-cluster implementations of the Gateway 
- [x] Update tests to ensure we have coverage for both types of gateway status, multi cluster (MGC) and singe (ISTIO etc ...)

**Comment by makslion** [comment]
plus one more tinny [ask](https://github.com/Kuadrant/multicluster-gateway-controller/pull/465#discussion_r1335582539) for this issue

**Comment by makslion** [comment]
seem like there are also two ways [[first](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/test/util/test_types.go#L25-L38), and [second](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/test/integration/dnspolicy_controller_test.go#L61-L93)] we build gateways for the integration suite. It would be a good idea to have only one

**Comment by pmccarthy** [comment]
Todo: Change the logic around the lookup of the "cluster" resource to take into account there might not be any cluster at all see https://github.com/Kuadrant/multicluster-gateway-controller/pull/465/files#r1324149471

**Comment by makslion** [comment]
in light of #644 and #629 the scope of this issue is limited to [this](https://github.com/Kuadrant/multicluster-gateway-controller/pull/465#discussion_r1335582539) ask. I've also included a gateway validation: we should only have one address types on the gateway
