### ISSUE TITLE
Automate adding created issues to the kuadrant MGC project

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/multicluster-gateway-controller#526]
Add a GH workflow to automatically add new issues created in the [MGC repo](https://github.com/Kuadrant/multicluster-gateway-controller) to the [Multicluster Gateway Controller](https://github.com/orgs/Kuadrant/projects/9) project.

See https://github.com/Kuadrant/kuadrant-operator/pull/235

**Comment by pmccarthy** [comment]
Added workflow using the existing "Auto-add to project" workflow, see https://github.com/orgs/Kuadrant/projects/9/workflows/11890083



![Image](https://github.com/Kuadrant/multicluster-gateway-controller/assets/1999769/842c3e21-50e3-44fb-9364-a43021faca4e)

**Comment by pmccarthy** [comment]
Seems there are 24 existing issues that have not been assigned. Adding the workflow doesn't update existing tickets so need to manually update these ones as a one-off step
