### ISSUE TITLE
bug: mgc controller getting OOMKilled repeatedly

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#538]
```
mgc-controller-manager-6484d98997-9tvmb        0/1     OOMKilled   4 (75s ago)   3m30s
```

After increasing the memory limit to 500Mi, the pod stays running.
The idle memory usage (no CRs created at this time) is around 150Mi

```
kubectl -n multicluster-gateway-controller-system top pod
NAME                                           CPU(cores)   MEMORY(bytes)
mgc-controller-manager-79d77c6976-89bxr        714m         150Mi
```

After a few minutes, this drops to 78Mi

```
kubectl -n multicluster-gateway-controller-system top pod
NAME                                           CPU(cores)   MEMORY(bytes)
mgc-controller-manager-79d77c6976-89bxr        498m         78Mi
```

**Comment by maleck13** [comment]
So would the solution here be a set of resource limits and requests?

**Comment by david-martin** [comment]
So right now, there are requests and limits set.
https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/config/manager/manager.yaml#L54-L60

Here's a few options.

1. Remove the limit.
This changes the pod to be [BestEffort](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#besteffort). 
It would probably negate the cause of the OOMKilled events in this case.
However, there are cons associated with BestEffort.

2. Up the limit to a value that prevents the OOMKilled events seen here, and have some room to spare e.g. 256Mi
We have limited data points at this time. In this issue we have seen 78 to 150Mi range of memory when idle. Unless/until we have additional data to make a more informed decision, it would be better to err on the side of caution. Additional data points could come from users (get the data once off based on usage, or reports of more OOMKilled events), or could come from testing (see point 3)

3. Introduce 1 or more different types of performance testing (load, stress etc..) to get additional data points, and set a more informed limit.

In my opinion, we should *not* do 1 because of the increased likelihood of the pod being killed if a node is under load.
Option 2 sounds pragmatic for the current stage the project is at.
Option 3 could be introduced at a future point.

**Comment by maleck13** [comment]
+1 to your suggestion option 2. Do you want to make that change
