### ISSUE TITLE
bug: Old mgc controller image used if already exists in cluster

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#541]
The imagePullPolicy is set to IfNotPresent, which led to an older image running (without gcp support).
This could lead to confusion if we use floating tags for images.
In this case it was 'main'.

If we don't intend to use a floating tag, we can maybe close this issue as it's unlikely to happen to end users.
However, that doesn't look to be the case as I was following the docs to deploy the controller.

**Comment by maleck13** [comment]
on a release branch, the plan would be to (for this release at least) use a vx.y.z tag. This is a floating tag but in theory should never be rebuilt as any fixes would increment the patch. Ultimately I tihnk we will move to using the SHA. So for me this is a fine issue to keep open around release process but probably not something we need to fix immediately WDYT

**Comment by maleck13** [comment]
So for main, I thikn we can set the image pull policy to be Always

**Comment by maleck13** [comment]
follow up https://github.com/Kuadrant/multicluster-gateway-controller/issues/546

**Comment by maleck13** [comment]
@david-martin once the image policy merges and with the follow up in place are you happy for us to close this?

**Comment by david-martin** [comment]
> once the image policy merges

That should solve the immediate issue, so yes 👍 
Thanks for creating #546.
