### ISSUE TITLE
docs: ManagedZone documentation needs some updates

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/multicluster-gateway-controller#543]
Following up on https://github.com/Kuadrant/multicluster-gateway-controller/issues/524

There are a few docs deficiencies which we should fix, including:

- Add better provider docs, especially for GCP (previous [providers](https://github.com/Kuadrant/multicluster-gateway-controller/blob/GH-258-GCP/docs/how-to/providers/providers.md doc should have its content merged in)
- Include a sample of how to create a `dnsProviderSecretRef` for AWS and GCP (perhaps covered by above)
- Formatting for spec fields seems broken e.g. - `ID` -> `id`
- Actually show how to create a ManagedZone resource, given that's what the doc title is...

**Comment by maleck13** [comment]
@jasonmadigan we also have this doc? https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/dnspolicy/dns-provider.md perhpaps linking to that?

**Comment by maleck13** [comment]
is this actually in progress? If so lets move to the iteration

**Comment by jasonmadigan** [comment]
@maleck13 yeah- I'm gonna incorporate some of the content from the old, deleted, [provider.md](https://github.com/Kuadrant/multicluster-gateway-controller/blob/GH-258-GCP/docs/how-to/providers/providers.md), into that one (and also make some changes on managed-zone.md

**Comment by jasonmadigan** [comment]
@maleck13 moved into this iteration
