### ISSUE TITLE
Kuadrant addon does not work on OpenShift by default

### ISSUE THREAD

**Issue by pehala** [Kuadrant/multicluster-gateway-controller#574]
Kuadrant addon relies on the existence of `olm/operatorhubio-catalog` CatalogSource, which is installed by default if you follow https://olm.operatorframework.io/docs/getting-started/. On OpenShift the OLM is by default and so there is no need to follow this guide, however, it does not have the aforementioned CatalogSource, for community operators it uses
 `openshift-marketplace/community-operators`.

Workaround for this is manually creating the CatalogSource that the addon expects by copying the one OpenShift uses.

**Comment by maleck13** [comment]
@david-martin @jasonmadigan I think the solution to this one for now, is to call out in the install doc that you need to do the above in an OpenShift cluster
