### ISSUE TITLE
Manually created tls secret gets deleted on listener/gateway deletion

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#585]
**Steps to Reproduce**
Create a secret of type `kubernetes.io/tls` - can get the contents of one by creating a gateway generating a secret
Create a listener with tls entry using the secret name.
The certificate should point to this secret and be setup
Delete the gateway/listener, the secret shouldn't be deleted but is.

**Comment by maleck13** [comment]
Yes this is currently expected behaviour. So I guess the test case needs updating

- TLSPolicy target a gateway
- So it will manage TLS for all HTTPS listeners defined as part of that gateway

This will become more configurable when we support targeting a listener by name as part of a policy

**Comment by mikenairn** [comment]
Yeah, this isn't a bug, it's expected. TLSPolicy is all or nothing currently, and we will be looking into how we can target specific listeners with policies (dns and tls) after mvp.  Using manually created secrets is still possible, but you can't use TLSPolicy as well.

Sorry, i thought we had updated the test script to reflect this already.

**Comment by laurafitzgerald** [comment]
Thanks for the clarification on this one. I'll go ahead and close it then. 👍
