### ISSUE TITLE
I should be able to follow the metrics guide, without any errors or issues

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#608]
Follow the guide here 
https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/metrics-walkthrough/

report and bugs and issues

**Comment by david-martin** [comment]
I would say this can be marked tested and verified in #608

**Comment by Ygnas** [comment]
> I would say this can be marked tested and verified in #598 @Ygnas what do you think?

Yeah, I haven't had any issues, but I was doing it so I could run it blindfolded. Wouldn't be bad for someone else to try it. Unless you think that testing my PR was enough as there is not much happening.

**Comment by david-martin** [comment]
> Unless you think that testing my PR was enough
I have also run through the walkthrough in detail and am satisfied it is tested and verified sufficiently for this release.
