### ISSUE TITLE
Investigate running the gateway API conformance tests against the hub gateway

### ISSUE THREAD

**Issue by pmccarthy** [Kuadrant/multicluster-gateway-controller#625]
**What**

Read https://gateway-api.sigs.k8s.io/concepts/conformance/#3-conformance-tests 

GWAPI version is currently 0.6.1

Attempt to execute these against a hub defined gateway

**Done**

- Tests executed fully (failures are fine)
- Document / provide script so that anyone can execute them

**Comment by makslion** [comment]
Results https://docs.google.com/document/d/1NxDioky-61FXYmelSTnbxTkiKPH84d6bx0f7mcgZjIU/edit?usp=sharing

**Comment by laurafitzgerald** [comment]
@makslion out of interest moreso what triggered the change sed 's/gateway-conformance/gw-conf/' in the above commit? It seems to be the bulk of the changes there.

**Comment by makslion** [comment]
Note that conformance tests are a bit funky right now. There is a [GEP](https://github.com/kubernetes-sigs/gateway-api/issues/1709) about it, so, hopefully, it will be a more pleasant experience running them.

**Comment by makslion** [comment]
closing this issue. Seems like people are satisfied with the investigation that was done and the first "follow-up" issue was created.
