### ISSUE TITLE
Update documentation for DNSPolicy (routingStrategy)

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#646]
**What**

Update the quick start guides and reference docs based on the work done for DNSPolicy in a single cluster context. (IE adding support for a routingStrategy) 

https://github.com/Kuadrant/architecture/pull/30/files

I also think we want to have a "single cluster" doc and "multi-cluster" doc and call out that the advanced load balancing and health checks, while can be used in a single cluster context, are not recommended and link to our multi-cluster setup doc if advanced load balancing is needed. Also we should call out that the `routingStrategy` simple is fine to use in a  multi-cluster environment

**Comment by mikenairn** [comment]
User-guide docs: https://github.com/Kuadrant/kuadrant-operator/pull/322

**Comment by mikenairn** [comment]
DNSPolicy and TLSPolicy Reference docs: https://github.com/Kuadrant/multicluster-gateway-controller/pull/684
