### ISSUE TITLE
Move to released 1.20.0 of istio

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#665]
Once a released version of istio 1.20.0 is available move to it. 
This should be available on the 14th of November as per [https://docs.google.com/presentation/d/1o9300tOlbsgSSqT1SSrUtMJn3T0DPsCaKIRJ6hB_MRo/edit?resourcekey=0-vz-W66d3_PbpjGLtiBu7TQ#slide=id.[…]776c6_0_90](https://docs.google.com/presentation/d/1o9300tOlbsgSSqT1SSrUtMJn3T0DPsCaKIRJ6hB_MRo/edit?resourcekey=0-vz-W66d3_PbpjGLtiBu7TQ#slide=id.g71589776c6_0_90)

It can also be checked here https://hub.docker.com/r/istio/pilot/tags

Please update the versions as per https://github.com/Kuadrant/multicluster-gateway-controller/pull/645/commits/3ae2d3ead7fdcc2861be390f011029846a25c345

- [ ] Update installed version of istioctl
- [ ] Update any changes in the `config/istio` dir

**Comment by sergioifg94** [comment]
Done as part of #645
