### ISSUE TITLE
release 0.3 manual docs testing

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#717]
**what**

This covers a set of tests to execute as part of release testing around documentation. It does not cover every doc, the aim is to cover what we consider to be the core / most valuable user facing docs.

**Process**

There is a corresponding `unified-kuadrant-layout` branch of the docs also  https://github.com/Kuadrant/docs.kuadrant.io/tree/unified-kuadrant-layout

Check out this branch and run the docs locally usinging `mkdocs serve`

-  [x] (cbrookes) Follow: https://docs.kuadrant.io/getting-started/ . Ensure it works as expected. Any issues should be reported as issues linked to this one. Validate that this works for both AWS and GCP
- [x]  (pbrookes) Follow https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/installation/control-plane-installation.md and install kuadrant into an existing k8s cluster that meets the dependency requirements
- [x] (rlawton) Follow the guide for installing the service protection components https://docs.kuadrant.io/multicluster-gateway-controller/docs/installation/service-protection-installation/ into a cluster that meets the pre-reqs
- [x] (@jasonmadigan) Follow https://docs.kuadrant.io/multicluster-gateway-controller/docs/gateways/define-and-place-a-gateway/ ensure you can complete the doc.
- [x] (@david-martin) Follow http://docs.kuadrant.io/multicluster-gateway-controller/docs/dnspolicy/dnspolicy-quickstart/ and ensure you can complete it without errors or issues
- [x] (@david-martin ) Follow the DNSPolicy health checks guide
- [x] (@jasonmadigan ) Follow through https://docs.kuadrant.io/multicluster-gateway-controller/docs/tlspolicy/tls-policy/ and ensure you can set up a TLSPolicy for a gateway without issues or error
  - Tested this alongside the define+place gateway

**Comment by david-martin** [comment]
> * Follow the DNSPolicy health checks guide

following what I can from /docs/dnspolicy/dns-health-checks/, I patched the DNSPolicy after going through the multi cluster walkthrough:
```json
[
  {
    "op": "add",
    "path": "/spec/healthCheck",
    "value": {
      "allowInsecureCertificates": true,
      "endpoint": "/",
      "expectedResponses": [200, 201, 301],
      "failureThreshold": 5,
      "port": 443,
      "protocol": "https"
    }
  }
]
```

`kubectl patch dnspolicy prod-web --type=json --patch-file=patch.json -n multi-cluster-gateways`

I'm not seeing any DNSHealthCheckProbe resources
```
kubectl get DNSHealthCheckProbe -A
No resources found
```

Here's the full DNSPolicy spec:
```yaml
spec:
  healthCheck:
    allowInsecureCertificates: true
    endpoint: /
    expectedResponses:
    - 200
    - 201
    - 301
    failureThreshold: 5
    port: 443
    protocol: https
  routingStrategy: loadbalanced
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: prod-web
```

`dig` and `curl` are working as expected for the HTTPRoute host `echo.dm.hcpapps.net`.

Full log of the policy controller [here](https://gist.github.com/david-martin/e245f36008c14c8e48970d4e361f27c5).

**Comment by maleck13** [comment]
@david-martin ok I will give it a go here also to reproduce

**Comment by david-martin** [comment]
@maleck13 The problem was the wildcard hostname in the Gateway listener.
I changed it to the full hostname and how the probes are created:

```
kubectl get -l kuadrant.io/gateway=prod-web dnshealthcheckprobes -A
NAMESPACE                NAME                        HEALTHY   LAST CHECKED
multi-cluster-gateways   172.31.201.0-prod-web-api   true      5s
multi-cluster-gateways   172.31.202.0-prod-web-api
```

I'll mark that test as OK now.

**Comment by maleck13** [comment]
Yeah figured that out also. Added https://github.com/Kuadrant/multicluster-gateway-controller/issues/726 as it is difficult to figure that out
