### ISSUE TITLE
Deploying the petstore app from a local clone of a public repo

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#746]
* Create an initial doc for the walkthrough
* Detail deploying the petstore app (public) via local clone of the now public repo
* PR into https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/how-to/api-walkthrough.md

**Comment by jasonmadigan** [comment]
Related: https://github.com/Kuadrant/multicluster-gateway-controller/pull/753

**Comment by david-martin** [comment]
Done in https://github.com/Kuadrant/api-quickstart/issues/4
