### ISSUE TITLE
Move TLSPolicy to Kuadrant Operator

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#766]
**What**

We are bringing the policy controllers into a single controller. We want to move the logic, CRDS, integration and e2e test for TLSPolicy into the kuadrant operator.

**Done**

- [x] Controller , CRDS and Tests moved over to kuadrant operator
- [x] Relevant Docs moved to kuadrant operator
- [x] Any relevant links updated in the Docs navigation

**Comment by mikenairn** [comment]
Closed by https://github.com/Kuadrant/kuadrant-operator/pull/416
