### ISSUE TITLE
Move DNS Controller into its own component

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#779]
**What**

With DNSPolicy moving to kuadrant operator, we need to move the DNS logic somewhere other than the MGC. To do this we will set up a new repo for the DNSController that will contain the logic to reconcile DNSRecords and HealthChecks

**Comment by mikenairn** [comment]
New Repo Created: https://github.com/kuadrant/kuadrant-dns-operator

**Comment by mikenairn** [comment]
Apart from doc updates and a few small tweaks this repo is ready https://github.com/Kuadrant/kuadrant-dns-operator.

Follow up tasks:

* https://github.com/Kuadrant/kuadrant-dns-operator/issues/10
* https://github.com/Kuadrant/kuadrant-dns-operator/issues/11
